# Generated by Django 3.1 on 2020-10-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recieve',
            new_name='Receive',
        ),
    ]
