# Generated by Django 3.1 on 2020-10-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20201007_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receive',
            name='receive_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='receive',
            name='stock',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sms.stock'),
        ),
        migrations.AlterField(
            model_name='receive',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
