# Generated by Django 3.1 on 2020-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20201008_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receive',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
